### ISSUE TITLE
enum.h is missing

### ISSUE THREAD

**Issue by BenHanson** [daminetreg/xxhr#11]
When I try to build an example on VS I get an error as it can't find <enum.h> in error.hpp.

**Comment by daminetreg** [comment]
Dear @BenHanson how did you compile the code base ? With https://tipi.build ? 

The current up-to-date code is at https://github.com/nxxm/xxhr

**Comment by BenHanson** [comment]
I am building with Visual Studio locally. Should https://github.com/nxxm/xxhr/tree/master/xxhr contain enum.h?

**Comment by daminetreg** [comment]
Ok you can build locally with tipi and generate a visual studio solution if you want ( tipi . -t vs-16-2019-win64-cxx17 ) and it will download the dependencies from the listing in the .tipi/deps or .nxxm/deps file.

Actually enum.h comes from the library better-enums, xxhr has some other libraries too.

**Comment by BenHanson** [comment]
I had a look in https://github.com/daminetreg/xxhr/blob/master/.nxxm/deps

Thanks
